// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

/**
 * @title IZKVerifier
 * @notice Interface for the Groth16 verifier contract generated by snarkjs.
 *
 * To generate a real verifier:
 *   1. Design the eligibility circuit in Circom (circuits/eligibility.circom)
 *   2. Run a trusted setup: `snarkjs groth16 setup`
 *   3. Export the Solidity verifier: `snarkjs zkey export solidityverifier`
 *   4. Deploy the generated verifier and set its address in VoteLedger
 */
interface IZKVerifier {
    function verifyProof(
        uint256[2]    calldata piA,
        uint256[2][2] calldata piB,
        uint256[2]    calldata piC,
        uint256[]     calldata publicSignals
    ) external view returns (bool);
}
