// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.24;

import "./IZKVerifier.sol";

/**
 * @title PlonkVerifier
 * @notice On-chain Plonk proof verifier for the EligibilityPlonk circuit.
 *
 * This file is a STUB — the real verifier is generated by snarkjs after
 * the circuit compilation and trusted setup phases:
 *
 *   # 1. Compile circuit
 *   circom circuits/eligibility_plonk.circom --r1cs --wasm --sym -o build/
 *
 *   # 2. Download universal Powers-of-Tau SRS (no ceremony needed for Plonk)
 *   snarkjs powersoftau new bn128 23 pot23_0000.ptau
 *   snarkjs powersoftau prepare phase2 pot23_0000.ptau pot23_final.ptau
 *
 *   # 3. Generate Plonk proving/verification keys
 *   snarkjs plonk setup build/eligibility_plonk.r1cs pot23_final.ptau \
 *           build/eligibility_plonk.zkey
 *
 *   # 4. Export Solidity verifier
 *   snarkjs zkey export solidityverifier build/eligibility_plonk.zkey \
 *           contracts/PlonkVerifier.sol
 *
 * The exported verifier has the signature:
 *   function verifyProof(bytes memory proof, uint[] memory pubSignals)
 *       public view returns (bool)
 *
 * This stub wraps that interface to satisfy IZKVerifier.
 * Replace the body of verifyProof() with the snarkjs-generated implementation.
 *
 * @dev DO NOT deploy this stub to mainnet.
 */
contract PlonkVerifier is IZKVerifier {

    /**
     * @notice Verify a Plonk proof.
     *
     * The piA/piB/piC fields are repurposed for Plonk:
     *   - piA[0..1]  = first 32 bytes of the serialised Plonk proof
     *   - piB[0][0..1], piB[1][0..1] = next 128 bytes
     *   - piC[0..1]  = final 32 bytes
     *   - publicSignals = [merkleRoot, nullifier, pollId, countryCode]
     *
     * In practice the generated verifier accepts (bytes proof, uint[] pubSignals).
     * Update the ABI and VoteLedger.castVote() accordingly when deploying the
     * real verifier.
     */
    function verifyProof(
        uint256[2]    calldata,  /* piA — unused in stub */
        uint256[2][2] calldata,  /* piB — unused in stub */
        uint256[2]    calldata,  /* piC — unused in stub */
        uint256[]     calldata   /* publicSignals */
    ) external pure override returns (bool) {
        // STUB — replace with snarkjs-generated Plonk verifier logic
        return true;
    }
}
