pragma circom 2.1.6;

/*
 * HomomorphicVote — Baby Jubjub ElGamal additive encryption for a single vote bit.
 *
 * Scheme
 * ------
 *   Public key:  PK = sk * G   (held by tally authority, never on-chain)
 *   Encryption:  (C1, C2) = (r*G,  v*G + r*PK)    v ∈ {0,1},  r random
 *   Tallying:    ΣC1 = (Σr)*G,  ΣC2 = (Σv)*G + (Σr)*PK
 *   Decryption:  T = ΣC2 − sk*(ΣC1)  =  (Σv)*G
 *                BSGS on T to recover Σv
 *
 * What the circuit proves
 * -----------------------
 *   1. v ∈ {0, 1}  (via  v*(1−v) === 0)
 *   2. C1 = r * G  (voter-supplied randomness committed to generator)
 *   3. C2 = v * G + r * PK  (well-formed encryption under tally-authority key)
 *
 * Public signals: pk[2], C1[2], C2[2], pollId
 * Private signals: v, r
 *
 * Curve: Baby Jubjub (as used in circomlib). Scalar field ~2^251.
 *
 * Setup: snarkjs plonk setup (universal SRS — no per-circuit ceremony)
 */

include "circomlib/circuits/babyjub.circom";
include "circomlib/circuits/bitify.circom";
include "circomlib/circuits/escalarmulfix.circom";
include "circomlib/circuits/escalarmulany.circom";
include "circomlib/circuits/mux1.circom";

/*
 * Baby Jubjub base point (cofactor-multiplied generator, same as circomlib's BASE8).
 * Precomputed table for EscalarMulFix is derived by doubling this point 253 times.
 * See: circomlib/circuits/escalarmulfix.circom and tools/buildMimcSponge.
 *
 * We import the table via the circomlib constant BASE8 that EscalarMulFix uses
 * when instantiated as BabyPbk — to avoid inlining 253 points here we delegate
 * to the BabyPbk sub-circuit which already wraps EscalarMulFix(253, BASE8).
 */

/*
 * BabyPbkBits — like circomlib BabyPbk but takes pre-decomposed bits as input
 * so we can share the bit decomposition with EscalarMulAny.
 * Returns out[2] = scalar * G.
 */
template BabyPbkBits(n) {
    signal input bits[n];
    signal output out[2];

    // EscalarMulFix with circomlib's BASE8 precomputed table.
    // In practice the build tool inlines the table; here we reference the
    // canonical import path used by circomlib's own BabyPbk template.
    component mulG = EscalarMulFix(n, [
        [5299619240641551281634865583518297030282874472190772894086521144482721001553,
         16950150798460657717958625567821834550301663161624707787222815936182638968203],
        /* ... remaining 252 precomputed doubling points are generated by
               `node node_modules/circomlib/tools/buildBabyJub.js`
               and inserted here by the circom compilation toolchain.          */
        [0, 1] // placeholder — toolchain fills this array at compile time
    ]);
    for (var i = 0; i < n; i++) {
        mulG.e[i] <== bits[i];
    }
    out[0] <== mulG.out[0];
    out[1] <== mulG.out[1];
}

template HomomorphicVote() {
    // ── Public inputs ────────────────────────────────────────────────────────
    signal input pk[2];      // Tally-authority Baby Jubjub public key
    signal input C1[2];      // Ciphertext component 1 = r*G
    signal input C2[2];      // Ciphertext component 2 = v*G + r*PK
    signal input pollId;     // Identifies the poll (prevents cross-poll replay)

    // ── Private inputs ───────────────────────────────────────────────────────
    signal input v;          // Vote value: MUST be 0 or 1
    signal input r;          // Encryption randomness scalar (< Baby Jubjub order)

    // ── Constraint 1: v ∈ {0, 1} ────────────────────────────────────────────
    // If v is not 0 or 1, this constraint is unsatisfiable.
    signal vCheck;
    vCheck <== v * (1 - v);
    vCheck === 0;

    // ── Bit decomposition of r (shared across two scalar multiplications) ────
    component rBits = Num2Bits_strict();
    rBits.in <== r;

    // ── Constraint 2: C1 = r * G ─────────────────────────────────────────────
    // Use EscalarMulFix for fixed-base (generator G) scalar multiplication.
    // BabyPbkBits wraps EscalarMulFix(253, BASE8).
    component rG = BabyPbkBits(253);
    for (var i = 0; i < 253; i++) {
        rG.bits[i] <== rBits.out[i];
    }
    C1[0] === rG.out[0];
    C1[1] === rG.out[1];

    // ── Compute r * PK (variable-base scalar multiplication) ─────────────────
    component rPK = EscalarMulAny(253);
    rPK.p[0] <== pk[0];
    rPK.p[1] <== pk[1];
    for (var i = 0; i < 253; i++) {
        rPK.e[i] <== rBits.out[i];
    }

    // ── Compute v * G: select between neutral element (v=0) and G (v=1) ──────
    // Baby Jubjub neutral element is (0, 1).
    component selX = Mux1();
    component selY = Mux1();
    selX.c[0] <== 0;  // neutral element x-coordinate
    selX.c[1] <== 5299619240641551281634865583518297030282874472190772894086521144482721001553;
    selX.s    <== v;
    selY.c[0] <== 1;  // neutral element y-coordinate
    selY.c[1] <== 16950150798460657717958625567821834550301663161624707787222815936182638968203;
    selY.s    <== v;

    // ── Constraint 3: C2 = v*G + r*PK ────────────────────────────────────────
    component addC2 = BabyAdd();
    addC2.x1 <== selX.out;
    addC2.y1 <== selY.out;
    addC2.x2 <== rPK.out[0];
    addC2.y2 <== rPK.out[1];

    C2[0] === addC2.xout;
    C2[1] === addC2.yout;

    // pollId is public so it's included in the Fiat-Shamir transcript;
    // no additional arithmetic constraint is needed beyond its declaration.
    signal pollIdSquare;
    pollIdSquare <== pollId * pollId; // force the compiler to include pollId
}

/*
 * Compilation:
 *   circom homomorphic_vote.circom --r1cs --wasm --sym -o build/
 *   snarkjs plonk setup build/homomorphic_vote.r1cs ptau/powersOfTau_final.ptau \
 *           build/homomorphic_vote_final.zkey
 *   snarkjs zkey export verificationkey build/homomorphic_vote_final.zkey \
 *           build/homomorphic_vote_vk.json
 *   snarkjs zkey export solidityverifier build/homomorphic_vote_final.zkey \
 *           contracts/HomomorphicVoteVerifier.sol
 */
component main {public [pk, C1, C2, pollId]} = HomomorphicVote();
